name: "EUR_USD_Dynamic_Regime"
version: "1.0"

live: true
data_source: "CSV"

api:
  key: "XtejxmiwNHZqDFk"
  app_id: "80720"

backtesting:
  start_date: "2020-01-01"
  end_date: "2024-12-31"
  initial_balance: 10000
  commission_per_lot: 7.0
  spread_pips: 1.2

# ----------------------------------------------------------------------------------
# General Strategy Settings
# ----------------------------------------------------------------------------------
strategy:
  name: "Dynamic Regime Strategy"
  description: "A strategy that adapts to market regimes using multiple indicators and timeframes."
  instruments: ["EUR/USD"]
  # Define all timeframes the strategy might need for calculations.
  timeframes: ["H1", "H4"]

  # ----------------------------------------------------------------------------------
  # 1. DEFINE INDICATORS
  # Centralized list of all indicators to be calculated. Each indicator gets a unique
  # name that will be referenced in the logic sections below.
  # ----------------------------------------------------------------------------------
  indicators:
    # Regime & Volatility Indicators (on H4 timeframe)
    - name: "regime_adx"
      timeframe: "H4"
      type: "ADX"
      params: { period: 14 }
    - name: "volatility_bbw"
      timeframe: "H4"
      type: "BBW" # Bollinger Bands Width
      params: { period: 20, std_dev: 2.0 }

    # Trending Strategy Indicators
    - name: "trend_ema_fast_H4"
      timeframe: "H4"
      type: "EMA"
      params: { period: 50 }
    - name: "trend_ema_slow_H4"
      timeframe: "H4"
      type: "EMA"
      params: { period: 200 }
    - name: "trend_ema_fast_H1"
      timeframe: "H1"
      type: "EMA"
      params: { period: 20 }
    - name: "trend_ema_slow_H1"
      timeframe: "H1"
      type: "EMA"
      params: { period: 50 }
    - name: "trend_macd_H1"
      timeframe: "H1"
      type: "MACD"
      params: { fast: 12, slow: 26, signal: 9 }
    - name: "trend_atr_H1"
      timeframe: "H1"
      type: "ATR"
      params: { period: 14 }

    # Ranging Strategy Indicators
    - name: "range_stoch_H1"
      timeframe: "H1"
      type: "STOCH"
      params: { k_period: 14, d_period: 3, smoothing: 3 }
    - name: "range_sr_H1"
      timeframe: "H1"
      type: "PIVOT" # Example for Support/Resistance
      params: { method: "classic" }
    - name: "range_atr_H1"
      timeframe: "H1"
      type: "ATR"
      params: { period: 14 }

  # ----------------------------------------------------------------------------------
  # 2. DEFINE MARKET REGIME
  # A set of rules to determine the current market state (TRENDING, RANGING, etc.).
  # Rules are evaluated in order; the first one that matches sets the regime.
  # ----------------------------------------------------------------------------------
  regime_filter:
    - when: # Defines a condition for a TRENDING market
        # Reference indicators by name. The system will get the latest value.
        - "regime_adx.adx > 25"
        # Example of using the volatility filter with a calculated percentile.
        - "volatility_bbw.width > percentile(volatility_bbw.width, 75)"
      then: "TRENDING"

    - when: # Defines a condition for a RANGING market
        - "regime_adx.adx < 20"
        - "volatility_bbw.width < percentile(volatility_bbw.width, 25)"
      then: "RANGING"

    - when: "default" # If no other condition is met
      then: "NEUTRAL"

  # ----------------------------------------------------------------------------------
  # 3. DEFINE SIGNAL LOGIC
  # Contains the entry and exit logic for each regime defined above.
  # ----------------------------------------------------------------------------------
  signal_logic:
    # --- Logic for when the market is TRENDING ---
    TRENDING:
      entry:
        - action: "BUY"
          condition_group: "all" # 'all' means AND
          rules:
            # Higher timeframe trend confirmation
            - "trend_ema_fast_H4 > trend_ema_slow_H4"
            # Entry timeframe trend alignment
            - "trend_ema_fast_H1 > trend_ema_slow_H1"
            # Momentum confirmation
            - "trend_macd_H1.histogram > 0"

        - action: "SELL"
          condition_group: "all"
          rules:
            - "trend_ema_fast_H4 < trend_ema_slow_H4"
            - "trend_ema_fast_H1 < trend_ema_slow_H1"
            - "trend_macd_H1.histogram < 0"
      exit:
        stop_loss:
          method: "ATR"
          # Explicitly state which ATR indicator to use for the stop loss calculation
          atr_indicator: "trend_atr_H1"
          multiplier: 2.0
        take_profit:
          # Partial take profit at 1:1 Risk/Reward
          - method: "risk_reward"
            rr_ratio: 1.0
            action: "partial_close"
            amount_percent: 50
          # Final take profit
          - method: "risk_reward"
            rr_ratio: 2.0
            action: "full_close"

    # --- Logic for when the market is RANGING ---
    RANGING:
      entry:
        - action: "BUY"
          condition_group: "all"
          rules:
            # Buy at support, confirmed by oversold stochastic and bullish candle
            - "price.low near range_sr_H1.S1" # 'near' implies a proximity check
            - "range_stoch_H1.k < 20"
            - "candlestick_pattern is bullish"

        - action: "SELL"
          condition_group: "all"
          rules:
            # Sell at resistance, confirmed by overbought stochastic and bearish candle
            - "price.high near range_sr_H1.R1"
            - "range_stoch_H1.k > 80"
            - "candlestick_pattern is bearish"
      exit:
        stop_loss:
          method: "ATR"
          atr_indicator: "range_atr_H1"
          multiplier: 1.5 # Tighter SL for ranging markets
        take_profit:
          # Target the other side of the range
          - method: "level"
            target: "opposite_level" # e.g., if entry is near S1, target is R1
            action: "full_close"

# Monitoring and Alerts Configuration
monitoring:
  performance_tracking:
    enabled: true
    metrics: ["profit_factor", "sharpe_ratio", "max_drawdown", "win_rate"]
  
  alerts:
    enabled: true
    channels: ["console", "file"]
    conditions:
      - "regime_change"
      - "position_opened"
      - "position_closed"
      - "risk_limit_breached"

