name: "EUR_USD_Dynamic_Regime"
version: "1.0"

live: false

api:
  key: "XtejxmiwNHZqDFk"
  app_id: "80720"

# Trading API Configuration
trading_api:
  type: "mt5_fastapi"  # Options: mt5_fastapi, deriv, etc.
  config:
    base_url: "http://192.168.0.164:8000"
    access_key: "e86f80f6-b69d-5593-b9a6-0b1d8df45a2d"

backtesting:
  data_source: "historical_live"
  start: "2025-06-28T00:00:00"
  end: "2025-06-28T14:00:00"
  initial_balance: 10000
  commission_per_lot: 7.0
  spread_pips: 1.2
  output_folder: "backtest_results"      # <--- Add this line
  save_datastore: true                   # <--- Add this line
  save_trade_history: true               # <--- Add this line

# ----------------------------------------------------------------------------------
# Strategy Configuration
# ----------------------------------------------------------------------------------
strategy:
  name: "Dynamic Regime Strategy"
  description: "A strategy that adapts to market regimes using multiple indicators and timeframes."
  symbols: ["Volatility 25 Index", "EURUSD"]
  timeframes: ["M1", "M5"]

  # ----------------------------------------------------------------------------------
  # 1. INDICATORS BY TIMEFRAME
  # ----------------------------------------------------------------------------------
  indicators:
    M1:
      - name: "regime_adx"
        type: "ADX"
        params: { period: 14 }
      - name: "volatility_bbw"
        type: "BBW"
        params: { period: 20, std_dev: 2.0 }
      - name: "trend_ema_fast"
        type: "EMA"
        params: { period: 50 }
      - name: "trend_ema_slow"
        type: "EMA"
        params: { period: 200 }
    M5:
      - name: "trend_ema_fast"
        type: "EMA"
        params: { period: 20 }
      - name: "trend_ema_slow"
        type: "EMA"
        params: { period: 50 }
      - name: "trend_macd"
        type: "MACD"
        params: { fast: 12, slow: 26, signal: 9 }
      - name: "trend_atr"
        type: "ATR"
        params: { period: 14 }
      # - name: "range_stoch"
      #   type: "STOCH"
      #   params: { k_period: 14, d_period: 3, smoothing: 3 }
      # - name: "range_sr"
      #   type: "PIVOT"
      #   params: { method: "classic" }
      - name: "range_atr"
        type: "ATR"
        params: { period: 14 }

  # ----------------------------------------------------------------------------------
  # 2. MARKET REGIME LOGIC
  # ----------------------------------------------------------------------------------
  regime_logic:
    rules:
      - name: "TRENDING"
        conditions:
          - "M1.regime_adx.adx > 25"
          - "M1.volatility_bbw.width.value > M1.volatility_bbw.width.percentile_75"
      - name: "RANGING"
        conditions:
          - "M1.regime_adx.adx < 20"
          - "M1.volatility_bbw.width.value < M1.volatility_bbw.width.percentile_25"
      - name: "NEUTRAL"
        conditions:
          - "default"

  # ----------------------------------------------------------------------------------
  # 3. TRADING LOGIC BY REGIME
  # ----------------------------------------------------------------------------------
  trading_logic:
    TRENDING:
      entries:
        BUY:
          conditions:
            - "M1.trend_ema_fast.value > M1.trend_ema_slow.value"
            - "M5.trend_ema_fast.value > M5.trend_ema_slow.value"
            - "M5.trend_macd.histogram > 0"
            - "price.close > price.open" # Additional bullish confirmation
        SELL:
          conditions:
            - "M1.trend_ema_fast.value < M1.trend_ema_slow.value"
            - "M5.trend_ema_fast.value < M5.trend_ema_slow.value"
            - "M5.trend_macd.histogram < 0"
            - "price.close < price.open" # Additional bearish confirmation
      exits:
        BUY:
          stop_loss:
            method: "ATR"
            indicator: "M5.trend_atr.value"
            multiplier: 2.0
          take_profit:
            method: "risk_reward"
            ratio: 2.0
        SELL:
          stop_loss:
            method: "ATR"
            indicator: "M5.trend_atr.value"
            multiplier: 2.0
          take_profit:
            method: "risk_reward"
            ratio: 2.0

    # RANGING:
    #   entries:
    #     BUY:
    #       conditions:
    #         # Replace vague "near" with specific range check
    #         - "price.low >= M5.range_sr.S1 * 0.9995" # Within 0.05% below support
    #         - "price.low <= M5.range_sr.S1 * 1.0005" # Within 0.05% above support
    #         - "M5.range_stoch.k < 20"
    #         # Replace vague "candlestick is bullish" with specific conditions
    #         - "price.close > price.open" # Bullish candle
    #         - "price.close > price.low + ((price.high - price.low) * 0.6)" # Strong close in upper portion
    #         - "price.close > price.previous_close" # Higher than previous close
    #     SELL:
    #       conditions:
    #         # Replace vague "near" with specific range check
    #         - "price.high <= M5.range_sr.R1 * 1.0005" # Within 0.05% above resistance
    #         - "price.high >= M5.range_sr.R1 * 0.9995" # Within 0.05% below resistance
    #         - "M5.range_stoch.k > 80"
    #         # Replace vague "candlestick is bearish" with specific conditions
    #         - "price.close < price.open" # Bearish candle
    #         - "price.close < price.high - ((price.high - price.low) * 0.6)" # Strong close in lower portion
    #         - "price.close < price.previous_close" # Lower than previous close
    #   exits:
    #     BUY:
    #       stop_loss:
    #         method: "ATR"
    #         indicator: "M5.range_atr"
    #         multiplier: 1.5
    #       take_profit:
    #         method: "level"
    #         target: "resistance"
    #         level: "M5.range_sr.R1"
    #     SELL:
    #       stop_loss:
    #         method: "ATR"
    #         indicator: "M5.range_atr"
    #         multiplier: 1.5
    #       take_profit:
    #         method: "level"
    #         target: "support"
    #         level: "M5.range_sr.S1"
    
    # NEUTRAL:
    #   entries:
    #     BUY:
    #       conditions:
    #         - "M1.trend_ema_fast.value > M1.trend_ema_slow.value"
    #         - "M5.trend_ema_fast.value > M5.trend_ema_slow.value"
    #         - "M5.range_stoch.k < 20"
    #     SELL:
    #       conditions:
    #         - "M1.trend_ema_fast.value < M1.trend_ema_slow.value"
    #         - "M5.trend_ema_fast.value < M5.trend_ema_slow.value"
    #         - "M5.range_stoch.k > 80"
    #   exits:
    #     BUY:
    #       stop_loss:
    #         method: "ATR"
    #         indicator: "M5.trend_atr.value"
    #         multiplier: 1.0
    #       take_profit:
    #         method: "risk_reward"
    #         ratio: 1.5
    #     SELL:
    #       stop_loss:
    #         method: "ATR"
    #         indicator: "M5.trend_atr.value"
    #         multiplier: 1.0
    #       take_profit:
    #         method: "risk_reward"
    #         ratio: 1.5

  # ----------------------------------------------------------------------------------
  # 4. RISK MANAGEMENT
  # ----------------------------------------------------------------------------------
  risk_management:
    risk_per_trade: 2.0  # Percentage of account equity to risk per trade (0.5-2% recommended)
    
    # Trade Management
    trade_management:
      max_concurrent_trades: 5  # Maximum number of open trades at any time
      allow_opposing_trades: false  # Whether to allow both long and short positions simultaneously
    
    # Drawdown Protection
    drawdown_protection:
      daily_loss_limit:
        enabled: true
        percentage: 3.0  # Stop trading if daily loss exceeds 3% of account equity
      weekly_loss_limit:
        enabled: true
        percentage: 5.0  # Stop trading if weekly loss exceeds 5% of account equity
      monthly_loss_limit:
        enabled: true
        percentage: 10.0  # Stop trading if monthly loss exceeds 10% of account equity
      max_consecutive_losses: 5  # Pause trading after 5 consecutive losses

    # Time Filters
    time_filters:
      # Avoid trading during low liquidity periods
      sessions:
        - name: "Asian"
          enabled: false  # Don't trade during Asian session
          start_time: "00:00"
          end_time: "08:00"
        - name: "London"
          enabled: true  # Allow trading during London session
          start_time: "08:00"
          end_time: "16:00"
        - name: "New York"
          enabled: true  # Allow trading during New York session
          start_time: "13:00"
          end_time: "21:00"
      daily_loss_limit:
        enabled: true
        percentage: 3.0  # Stop trading if daily loss exceeds 3% of account equity
      weekly_loss_limit:
        enabled: true
        percentage: 5.0  # Stop trading if weekly loss exceeds 5% of account equity
      monthly_loss_limit:
        enabled: true
        percentage: 10.0  # Stop trading if monthly loss exceeds 10% of account equity
      max_consecutive_losses: 5  # Pause trading after 5 consecutive losses