name: "EUR_USD_Dynamic_Regime"
version: "1.0"

live: false

# Trading API Configuration
trading_api:
  type: "mt5_fastapi"  # Options: mt5_fastapi, deriv, etc.
  config:
    base_url: "http://192.168.0.164:8000"
    access_key: "e86f80f6-b69d-5593-b9a6-0b1d8df45a2d"

backtesting:
  data_source: "historical_live"
  start: "2025-01-27T00:00:00"
  end: "2025-06-26T14:00:00"
  initial_balance: 10000
  commission_per_lot: 0.0
  spread_pips: 1.2
  output_folder: "backtest_results"      # <--- Add this line
  save_datastore: true                   # <--- Add this line
  save_trade_history: true               # <--- Add this line

# ----------------------------------------------------------------------------------
# Strategy Configuration
# ----------------------------------------------------------------------------------
strategy:
  name: "Dynamic Regime Strategy"
  description: "A strategy that adapts to market regimes using multiple indicators and timeframes."
  symbols: ["EURUSD"]
  timeframes: ["M15", "H1"]

  # ----------------------------------------------------------------------------------
  # 1. INDICATORS BY TIMEFRAME
  # ----------------------------------------------------------------------------------
  indicators:
    M15:
      - name: "regime_adx"
        type: "ADX"
        params: { period: 14 }
      - name: "volatility_bbw"
        type: "BBW"
        params: { period: 20, std_dev: 2.0 }
      - name: "trend_ema_fast"
        type: "EMA"
        params: { period: 50 }
      - name: "trend_ema_slow"
        type: "EMA"
        params: { period: 200 }
    H1:
      - name: "trend_ema_fast"
        type: "EMA"
        params: { period: 20 }
      - name: "trend_ema_slow"
        type: "EMA"
        params: { period: 50 }
      - name: "trend_macd"
        type: "MACD"
        params: { fast: 12, slow: 26, signal: 9 }
      - name: "trend_atr"
        type: "ATR"
        params: { period: 14 }
      - name: "range_sr"
        type: "S&R"
        params: { distance: 10, prominence: 0.025 }
      - name: "range_stoch"
        type: "STOCH"
        params: { k_period: 14, d_period: 3, smoothing: 3 }
      # - name: "range_pivot"
      #   type: "PIVOT"
      #   params: { method: "classic" }
      - name: "range_atr"
        type: "ATR"
        params: { period: 14 }

  # ----------------------------------------------------------------------------------
  # 2. MARKET REGIME LOGIC
  # ----------------------------------------------------------------------------------
  regime_logic:
    rules:
      - name: "TRENDING"
        conditions:
          - "M15;regime_adx;adx > 25"
          - "M15;volatility_bbw;width;value > M15;volatility_bbw;width;percentile_75"
      - name: "RANGING"
        conditions:
          - "M15;regime_adx;adx < 20"
          - "M15;volatility_bbw;width;value < M15;volatility_bbw;width;percentile_25"
      - name: "NEUTRAL"
        conditions:
          - "default"

  # ----------------------------------------------------------------------------------
  # 3. TRADING LOGIC BY REGIME
  # ----------------------------------------------------------------------------------
  trading_logic:
    TRENDING:
      entries:
        BUY:
          conditions:
            - "M15;trend_ema_fast;value > M15;trend_ema_slow;value"
            - "H1;trend_ema_fast;value > H1;trend_ema_slow;value"
            - "H1;trend_macd;histogram > 0"
            - "H1;trend_macd;cross > 0"
            - "price.close > price.open" # Additional bullish confirmation
        SELL:
          conditions:
            - "M15;trend_ema_fast;value < M15;trend_ema_slow;value"
            - "H1;trend_ema_fast;value < H1;trend_ema_slow;value"
            - "H1;trend_macd;histogram < 0"
            - "H1;trend_macd;cross > 0"
            - "price.close < price.open" # Additional bearish confirmation
      exits:
        BUY:
          stop_loss:
            method: "ATR"
            indicator: "H1;trend_atr;value"
            multiplier: 1.5
          take_profit:
            method: "risk_reward"
            ratio: 4.0
        SELL:
          stop_loss:
            method: "ATR"
            indicator: "H1;trend_atr;value"
            multiplier: 1.5
          take_profit:
            method: "risk_reward"
            ratio: 4.0

    # RANGING:
    #   entries:
    #     BUY:
    #       conditions:
    #         # Replace vague "near" with specific range check
    #         - "price.low >= H1;range_sr;S1 * 0.992" # Within 0.8% below support
    #         - "price.low <= H1;range_sr;S1 * 1.008" # Within 0.8% above support
    #         - "H1;range_stoch;k < 20"
    #         # Replace vague "candlestick is bullish" with specific conditions
    #         # - "price.close > price.open" # Bullish candle
    #         # - "price.close > price.low + ((price.high - price.low) * 0.6)" # Strong close in upper portion
    #         # - "price.close > price.previous_close" # Higher than previous close
    #     SELL:
    #       conditions:
    #         # Replace vague "near" with specific range check
    #         - "price.high <= H1;range_sr;R1 * 1.008" # Within 0.8% above resistance
    #         - "price.high >= H1;range_sr;R1 * 0.992" # Within 0.8% below resistance
    #         - "H1;range_stoch;k > 80"
    #         # Replace vague "candlestick is bearish" with specific conditions
    #         # - "price.close < price.open" # Bearish candle
    #         # - "price.close < price.high - ((price.high - price.low) * 0.6)" # Strong close in lower portion
    #         # - "price.close < price.previous_close" # Lower than previous close
    #   exits:
    #     BUY:
    #       stop_loss:
    #         method: "ATR"
    #         indicator: "H1;range_atr;value"
    #         multiplier: 1.5
    #       # take_profit:
    #       #   method: "level"
    #       #   target: "resistance"
    #       #   level: "H1;range_sr;R1"
    #       take_profit:
    #         method: "risk_reward"
    #         ratio: 3.0
    #     SELL:
    #       stop_loss:
    #         method: "ATR"
    #         indicator: "H1;range_atr;value"
    #         multiplier: 1.5
    #       # take_profit:
    #       #   method: "level"
    #       #   target: "support"
    #       #   level: "H1;range_sr;S1"
    #       take_profit:
    #         method: "risk_reward"
    #         ratio: 3.0

  # ----------------------------------------------------------------------------------
  # 4. RISK MANAGEMENT
  # ----------------------------------------------------------------------------------
  risk_management:
    risk_per_trade: 1.0  # Percentage of account equity to risk per trade (0.5-2% recommended)
    minimum_rrr: 1.5 # Minimum reward-to-risk ratio required to open a trade
    
    # Trade Management
    trade_management:
      max_concurrent_trades: 3  # Maximum number of open trades at any time
      allow_opposing_trades: false  # Whether to allow both long and short positions simultaneously

      # NOTE: This setting is always false out to avoid closing positions on regime change
      close_with_regime_change: false  # Close all positions for a symbol if its regime changes

    # Drawdown Protection
    drawdown_protection:
      daily_loss_limit:
        enabled: true
        percentage: 5.0  # Stop trading if daily loss exceeds 5% of account equity
      weekly_loss_limit:
        enabled: true
        percentage: 10.0  # Stop trading if weekly loss exceeds 10% of account equity
      monthly_loss_limit:
        enabled: true
        percentage: 20.0  # Stop trading if monthly loss exceeds 20% of account equity

      max_consecutive_losses: 100  # Stop trading entirely after 100 consecutive losses

    # Time Filters
    time_filters:
      # Avoid trading during low liquidity periods
      sessions:
        - name: "Default"
          enabled: true  # Allow trading during default session
          start_time: "00:00"
          end_time: "23:59"
        # - name: "Asian"
        #   enabled: false  # Don't trade during Asian session
        #   start_time: "00:00"
        #   end_time: "08:00"
        # - name: "London"
        #   enabled: true  # Allow trading during London session
        #   start_time: "08:00"
        #   end_time: "16:00"
        # - name: "New York"
        #   enabled: true  # Allow trading during New York session
        #   start_time: "13:00"
        #   end_time: "21:00"