name: "EUR_USD_Dynamic_Regime"
version: "1.0"

live: true
data_source: "CSV"

api:
  key: "XtejxmiwNHZqDFk"
  app_id: "80720"

backtesting:
  start_date: "2020-01-01"
  end_date: "2024-12-31"
  initial_balance: 10000
  commission_per_lot: 7.0
  spread_pips: 1.2

strategy:
  name: "Dynamic Regime Strategy"
  description: "A strategy that adapts to market regimes using multiple indicators and timeframes."
  instruments: ["EUR/USD"]
  timeframes: ["1H", "4H"]

  market_regime:
    primary_indicator: "ADX"
    adx_period: 14
    trending_threshold: 25
    ranging_threshold: 20
    confirmation_bars: 2
    
    volatility_filter:
      enabled: true
      indicator: "BBW"
      bb_period: 20
      bb_std_dev: 2.0
      low_vol_percentile: 25
      high_vol_percentile: 75

  trending_strategy:
    timeframes:
      regime_detection: "4H"
      entry_signals: "1H"
    
    indicators:
      h4_ema_fast: 50
      h4_ema_slow: 200
      h1_ema_fast: 20
      h1_ema_slow: 50
      macd: [12, 26, 9]
      atr_period: 14
    
    entry_rules:
      require_ema_alignment: true
      require_macd_confirmation: true
      require_candlestick_pattern: false
    
    exit_rules:
      initial_rr_ratio: 2.0
      partial_profit_rr: 1.0
      partial_profit_percent: 50
      trailing_stop_method: "ATR"  
      trailing_atr_multiplier: 2.0

  ranging_strategy:
    timeframes:
      regime_detection: "4H"
      entry_signals: "1H"
    
    indicators:
      stochastic: [14, 3, 3]
      atr_period: 14
      support_resistance_method: "PIVOT"
    
    entry_rules:
      stochastic_oversold: 20
      stochastic_overbought: 80
      require_divergence: false
      require_candlestick_pattern: true
    
    exit_rules:
      target_opposite_level: true
      minimum_rr_ratio: 1.5
      use_mid_range_tp: true

# Risk Management Configuration
risk_management:
  position_sizing:
    method: "FIXED_FRACTIONAL"
    risk_per_trade_percent: 1.0
    max_sl_pips: 70

  account_protection:
    daily_loss_limit_percent: 3.0
    weekly_loss_limit_percent: 8.0
    max_concurrent_positions: 3

  correlation_limits:
    max_correlation_exposure: 0.7

# Monitoring and Alerts Configuration
monitoring:
  performance_tracking:
    enabled: true
    metrics: ["profit_factor", "sharpe_ratio", "max_drawdown", "win_rate"]
  
  alerts:
    enabled: true
    channels: ["console", "file"]
    conditions:
      - "regime_change"
      - "position_opened"
      - "position_closed"
      - "risk_limit_breached"

